version: '3'

volumes:
  pg_data_foodgram:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    image: my0user/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    env_file: .env
    image: my0user/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: my0user/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    ports:
      - 8000:80
